compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "buku"
database_id = "kodeantum"
preview_database_id = "DB" # Required for Pages local development


